# Generated by Django 5.2.16 on 2026-07-22 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="environment",
            options={
                "ordering": ["-is_default", "created_at", "id"],
                "verbose_name": "运行环境",
                "verbose_name_plural": "运行环境",
            },
        ),
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ["created_at", "id"],
                "verbose_name": "角色",
                "verbose_name_plural": "角色",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "用户", "verbose_name_plural": "用户"},
        ),
        migrations.AlterModelTableComment(
            name="environment",
            table_comment="自动化运行环境配置表",
        ),
        migrations.AlterModelTableComment(
            name="role",
            table_comment="角色信息表",
        ),
        migrations.AlterModelTableComment(
            name="user",
            table_comment="用户信息表",
        ),
        migrations.AlterModelTable(
            name="environment",
            table="aibet_environment",
        ),
        migrations.AlterModelTable(
            name="role",
            table="aibet_role",
        ),
        migrations.AlterModelTable(
            name="user",
            table="aibet_user",
        ),
        migrations.CreateModel(
            name="AutomationModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app",
                    models.CharField(
                        choices=[("frontend", "前端"), ("backend", "后台")],
                        max_length=20,
                        verbose_name="所属端",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模块名称")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "自动化模块",
                "verbose_name_plural": "自动化模块",
                "db_table": "aibet_automation_module",
                "db_table_comment": "自动化业务模块表",
                "ordering": ["app", "sort_order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("app", "name"), name="uniq_automation_app_module"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AutomationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="任务名称")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("api", "接口测试"),
                            ("ui", "UI 测试"),
                            ("scenario", "场景测试"),
                        ],
                        max_length=20,
                        verbose_name="测试类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("passed", "已通过"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        default="手动执行", max_length=100, verbose_name="执行策略"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="automation_tasks",
                        to="platform_api.environment",
                        verbose_name="运行环境",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="platform_api.automationmodule",
                        verbose_name="业务模块",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="automation_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="负责人",
                    ),
                ),
            ],
            options={
                "verbose_name": "自动化任务",
                "verbose_name_plural": "自动化任务",
                "db_table": "aibet_automation_task",
                "db_table_comment": "自动化执行任务表",
                "ordering": ["-updated_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ApiInterface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="接口名称")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                        ],
                        max_length=10,
                        verbose_name="请求方法",
                    ),
                ),
                ("path", models.CharField(max_length=500, verbose_name="请求路径")),
                (
                    "module_name",
                    models.CharField(max_length=100, verbose_name="所属模块"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="接口描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_interfaces",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "接口资产",
                "verbose_name_plural": "接口资产",
                "db_table": "aibet_api_interface",
                "db_table_comment": "自动化接口资产表",
                "ordering": ["-updated_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("method", "path"), name="uniq_api_method_path"
                    )
                ],
            },
        ),
    ]
