# Generated by Django 5.2.16 on 2026-07-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_api", "0003_comment_framework_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiinterface",
            name="headers",
            field=models.JSONField(blank=True, default=dict, verbose_name="请求头"),
        ),
        migrations.AddField(
            model_name="apiinterface",
            name="request_params",
            field=models.JSONField(blank=True, default=dict, verbose_name="请求参数"),
        ),
    ]
