# Generated by Django 5.2.16 on 2026-07-22 04:04

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def seed_execution_details(apps, schema_editor):
    ApiInterface = apps.get_model('platform_api', 'ApiInterface')
    AutomationTask = apps.get_model('platform_api', 'AutomationTask')
    AutomationTaskResult = apps.get_model('platform_api', 'AutomationTaskResult')
    executed_at = timezone.now()
    for task in AutomationTask.objects.select_related('module'):
        interfaces = ApiInterface.objects.filter(module_name=task.module.name)
        for index, interface in enumerate(interfaces):
            detail_status = 'failed' if task.status == 'failed' and index == 0 else task.status
            AutomationTaskResult.objects.get_or_create(
                task=task,
                interface=interface,
                defaults={
                    'status': detail_status,
                    'duration_ms': None if detail_status in ('pending', 'running') else 118 + index * 73,
                    'response_message': '断言通过' if detail_status == 'passed' else ('响应状态码不符合预期' if detail_status == 'failed' else ''),
                    'executed_at': executed_at if detail_status in ('passed', 'failed') else None,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ("platform_api", "0006_normalize_automation_modules"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationTaskResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("passed", "已通过"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="执行结果",
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="耗时（毫秒）"
                    ),
                ),
                (
                    "response_message",
                    models.TextField(blank=True, default="", verbose_name="执行信息"),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="执行时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "interface",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="task_results",
                        to="platform_api.apiinterface",
                        verbose_name="执行接口",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_details",
                        to="platform_api.automationtask",
                        verbose_name="自动化任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务执行明细",
                "verbose_name_plural": "任务执行明细",
                "db_table": "aibet_automation_task_result",
                "db_table_comment": "自动化任务接口执行明细表",
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task", "interface"), name="uniq_task_interface_result"
                    )
                ],
            },
        ),
        migrations.RunPython(seed_execution_details, migrations.RunPython.noop),
    ]
