# Generated by Django 5.2.16 on 2026-07-22 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_api", "0007_automationtaskresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automationtaskresult",
            name="interface",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_results",
                to="platform_api.apiinterface",
                verbose_name="执行接口",
            ),
        ),
    ]
