# Generated by Django 5.2.16 on 2026-07-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "platform_api",
            "0009_remove_automationtaskresult_uniq_task_interface_result_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="apiinterface",
            name="assertions",
            field=models.JSONField(blank=True, default=dict, verbose_name="接口断言"),
        ),
        migrations.AddField(
            model_name="automationtaskresult",
            name="assertions",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="接口断言快照"
            ),
        ),
    ]
