# Generated by Django 5.2.16 on 2026-07-22 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_api", "0010_apiinterface_assertions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitorExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "execution_no",
                    models.PositiveIntegerField(default=1, verbose_name="执行批次"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "执行中"),
                            ("passed", "已通过"),
                            ("failed", "失败"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="执行结果",
                    ),
                ),
                (
                    "interface_total",
                    models.PositiveIntegerField(default=0, verbose_name="接口总数"),
                ),
                (
                    "failure_count",
                    models.PositiveIntegerField(default=0, verbose_name="失败数量"),
                ),
                (
                    "average_duration_ms",
                    models.PositiveIntegerField(default=0, verbose_name="平均耗时（毫秒）"),
                ),
                (
                    "message",
                    models.TextField(blank=True, default="", verbose_name="执行信息"),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
            ],
            options={
                "verbose_name": "监控执行记录",
                "verbose_name_plural": "监控执行记录",
                "db_table": "aibet_monitor_execution",
                "db_table_comment": "监控中心任务执行记录表",
                "ordering": ["-started_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="MonitorApiConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="接口名称")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                        ],
                        max_length=10,
                        verbose_name="请求方法",
                    ),
                ),
                ("path", models.CharField(max_length=500, verbose_name="请求路径")),
                ("module_name", models.CharField(max_length=100, verbose_name="所属模块")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="接口描述"),
                ),
                (
                    "headers",
                    models.JSONField(blank=True, default=dict, verbose_name="请求头"),
                ),
                (
                    "request_params",
                    models.JSONField(blank=True, default=dict, verbose_name="请求参数"),
                ),
                (
                    "assertions",
                    models.JSONField(blank=True, default=dict, verbose_name="接口断言"),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="启用状态")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_monitor_configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "source_interface",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monitor_configs",
                        to="platform_api.apiinterface",
                        verbose_name="来源接口",
                    ),
                ),
            ],
            options={
                "verbose_name": "监控接口配置",
                "verbose_name_plural": "监控接口配置",
                "db_table": "aibet_monitor_api_config",
                "db_table_comment": "监控中心接口配置表",
                "ordering": ["-updated_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="MonitorExecutionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_api_config_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="来源监控接口ID"
                    ),
                ),
                (
                    "interface_name",
                    models.CharField(default="", max_length=200, verbose_name="接口名称快照"),
                ),
                (
                    "method",
                    models.CharField(default="", max_length=10, verbose_name="请求方法快照"),
                ),
                (
                    "path",
                    models.CharField(default="", max_length=500, verbose_name="请求路径快照"),
                ),
                (
                    "url",
                    models.CharField(
                        default="", max_length=800, verbose_name="完整请求地址快照"
                    ),
                ),
                (
                    "module_name",
                    models.CharField(default="", max_length=100, verbose_name="所属模块快照"),
                ),
                (
                    "headers",
                    models.JSONField(blank=True, default=dict, verbose_name="请求头快照"),
                ),
                (
                    "request_params",
                    models.JSONField(blank=True, default=dict, verbose_name="请求参数快照"),
                ),
                (
                    "assertions",
                    models.JSONField(blank=True, default=dict, verbose_name="接口断言快照"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "执行中"),
                            ("passed", "已通过"),
                            ("failed", "失败"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="执行结果",
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="耗时（毫秒）"
                    ),
                ),
                (
                    "response_message",
                    models.TextField(blank=True, default="", verbose_name="执行信息"),
                ),
                (
                    "executed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="执行时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="platform_api.monitorexecution",
                        verbose_name="监控执行记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "监控执行明细",
                "verbose_name_plural": "监控执行明细",
                "db_table": "aibet_monitor_execution_detail",
                "db_table_comment": "监控中心接口执行明细表",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MonitorTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="任务名称")),
                (
                    "module_name",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="任务模块"
                    ),
                ),
                (
                    "interval_value",
                    models.PositiveIntegerField(default=1, verbose_name="执行间隔"),
                ),
                (
                    "interval_unit",
                    models.CharField(
                        choices=[("minute", "分钟"), ("hour", "小时"), ("day", "天")],
                        default="minute",
                        max_length=20,
                        verbose_name="间隔单位",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="启用状态")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("passed", "已通过"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="最近执行状态",
                    ),
                ),
                (
                    "notification",
                    models.JSONField(blank=True, default=dict, verbose_name="通知配置"),
                ),
                (
                    "last_run_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="最近执行时间"),
                ),
                (
                    "next_run_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="下次执行时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "api_configs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="monitor_tasks",
                        to="platform_api.monitorapiconfig",
                        verbose_name="监控接口",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_monitor_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monitor_tasks",
                        to="platform_api.environment",
                        verbose_name="监控环境",
                    ),
                ),
            ],
            options={
                "verbose_name": "监控任务",
                "verbose_name_plural": "监控任务",
                "db_table": "aibet_monitor_task",
                "db_table_comment": "监控中心定时任务表",
                "ordering": ["-updated_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="monitorexecution",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="platform_api.monitortask",
                verbose_name="监控任务",
            ),
        ),
        migrations.CreateModel(
            name="MonitorAlarm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("warning", "警告"), ("error", "错误")],
                        default="error",
                        max_length=20,
                        verbose_name="报警级别",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "未处理"), ("handled", "已处理")],
                        default="open",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                ("message", models.TextField(verbose_name="报警内容")),
                (
                    "handled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="处理时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_monitor_alarms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="处理人",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alarms",
                        to="platform_api.monitorexecution",
                        verbose_name="执行记录",
                    ),
                ),
                (
                    "detail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alarms",
                        to="platform_api.monitorexecutiondetail",
                        verbose_name="执行明细",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alarms",
                        to="platform_api.monitortask",
                        verbose_name="监控任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "监控报警记录",
                "verbose_name_plural": "监控报警记录",
                "db_table": "aibet_monitor_alarm",
                "db_table_comment": "监控中心报警记录表",
                "ordering": ["-created_at", "id"],
            },
        ),
    ]
