# Generated by Django 5.2.16 on 2026-07-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_api", "0011_monitorexecution_monitorapiconfig_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiinterface",
            name="api_type",
            field=models.CharField(
                blank=True, default="默认", max_length=100, verbose_name="接口类型"
            ),
        ),
        migrations.AddField(
            model_name="apiinterface",
            name="can_execute_in_task",
            field=models.BooleanField(default=True, verbose_name="可被任务执行"),
        ),
        migrations.AddField(
            model_name="monitorapiconfig",
            name="api_type",
            field=models.CharField(
                blank=True, default="默认", max_length=100, verbose_name="接口类型"
            ),
        ),
        migrations.AddField(
            model_name="monitorexecutiondetail",
            name="source_interface_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="来源自动化接口ID"
            ),
        ),
        migrations.AddField(
            model_name="monitortask",
            name="api_type",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="接口类型"
            ),
        ),
        migrations.AddField(
            model_name="monitortask",
            name="automation_interfaces",
            field=models.ManyToManyField(
                blank=True,
                related_name="monitor_tasks",
                to="platform_api.apiinterface",
                verbose_name="自动化接口",
            ),
        ),
    ]
