# Generated by Django 5.2.16 on 2026-07-23 07:11

import django.db.models.deletion
from django.db import migrations, models


def copy_legacy_modules(apps, schema_editor):
    AutomationTask = apps.get_model('platform_api', 'AutomationTask')
    for task in AutomationTask.objects.exclude(module_id=None).iterator():
        task.modules.add(task.module_id)


class Migration(migrations.Migration):

    dependencies = [
        ("platform_api", "0015_reorder_business_modules"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationtask",
            name="modules",
            field=models.ManyToManyField(
                blank=True,
                related_name="tasks",
                to="platform_api.automationmodule",
                verbose_name="业务模块",
            ),
        ),
        migrations.AlterField(
            model_name="automationtask",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="legacy_tasks",
                to="platform_api.automationmodule",
                verbose_name="默认业务模块",
            ),
        ),
        migrations.RunPython(copy_legacy_modules, migrations.RunPython.noop),
    ]
