# Generated by Django 5.2.14 on 2026-07-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_api", "0017_merge_split_automation_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationtaskresult",
            name="response_log",
            field=models.TextField(blank=True, default="", verbose_name="失败响应日志"),
        ),
    ]
