# Generated by Django 5.2.14 on 2026-07-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0018_automationtaskresult_response_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='notification_message',
            field=models.TextField(blank=True, default='', verbose_name='飞书通知信息'),
        ),
        migrations.AddField(
            model_name='automationtask',
            name='notification_status',
            field=models.CharField(choices=[('pending', '待发送'), ('sent', '发送成功'), ('failed', '发送失败'), ('disabled', '未配置')], default='pending', max_length=20, verbose_name='飞书通知状态'),
        ),
        migrations.AddField(
            model_name='automationtask',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='飞书通知时间'),
        ),
    ]
