# Generated by Django 5.2.16 on 2026-07-27 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_api", "0021_normalize_api_interface_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiinterface",
            name="reference_enabled",
            field=models.BooleanField(default=False, verbose_name="启用关联标记"),
        ),
        migrations.AddField(
            model_name="apiinterface",
            name="reference_interface",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referenced_by_interfaces",
                to="platform_api.apiinterface",
                verbose_name="关联接口",
            ),
        ),
        migrations.AddField(
            model_name="apiinterface",
            name="response_extracts",
            field=models.JSONField(
                blank=True, default=list, verbose_name="关联响应提取规则"
            ),
        ),
    ]
