# Generated by Django 5.2.14 on 2026-07-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0026_apiinterface_parameterizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFactoryExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100, verbose_name='工具名称')),
                ('email', models.EmailField(max_length=254, verbose_name='会员邮箱')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='金额')),
                ('member_id', models.CharField(blank=True, default='', max_length=100, verbose_name='会员ID')),
                ('adjustment_id', models.CharField(blank=True, default='', max_length=100, verbose_name='审批单据ID')),
                ('status', models.CharField(choices=[('running', '执行中'), ('passed', '已完成'), ('failed', '执行失败')], default='running', max_length=20, verbose_name='执行状态')),
                ('message', models.TextField(blank=True, default='', verbose_name='执行信息')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('environment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_factory_executions', to='platform_api.environment', verbose_name='运行环境')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_factory_executions', to='platform_api.user', verbose_name='操作人')),
            ],
            options={'verbose_name': '数据工厂执行记录', 'verbose_name_plural': '数据工厂执行记录', 'db_table': 'aibet_data_factory_execution', 'db_table_comment': '数据工厂执行记录表', 'ordering': ['-executed_at', '-id']},
        ),
    ]
