# Generated by Django 5.2.16 on 2026-08-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_api", "0029_datafactoryexecution_generated_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_via",
            field=models.CharField(
                choices=[("manual", "手动创建"), ("lark_sso", "Lark 免登")],
                default="manual",
                max_length=20,
                verbose_name="创建来源",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="lark_open_id",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="Lark Open ID"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="lark_union_id",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                unique=True,
                verbose_name="Lark Union ID",
            ),
        ),
    ]
