# Generated by Django 5.2.16 on 2026-08-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_api", "0030_add_lark_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="platform_account",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="平台账号"
            ),
        ),
    ]
