# Generated by Django 5.2.14 on 2026-08-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_api", "0033_user_environment_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitortask",
            name="login_password_encrypted",
            field=models.TextField(blank=True, default="", verbose_name="目标系统登录密码（加密）"),
        ),
    ]
