# Generated by Django 5.2.14 on 2026-08-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_api", "0034_monitortask_login_password_encrypted"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationtask",
            name="login_password_encrypted",
            field=models.TextField(blank=True, default="", verbose_name="目标系统登录密码（加密）"),
        ),
    ]
