# Generated by Django 5.2.14 on 2026-08-05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('platform_api', '0035_automationtask_login_password_encrypted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationtask',
            name='login_password_encrypted',
        ),
    ]
