# Generated by Django 5.2.14 on 2026-08-06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('platform_api', '0036_remove_automationtask_login_password_encrypted')]

    operations = [
        migrations.CreateModel(
            name='TestCasePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='用例包名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='用例内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_testcase_packages', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={'verbose_name': '用例包', 'verbose_name_plural': '用例包', 'db_table': 'aibet_testcase_package', 'db_table_comment': '测试用例包表', 'ordering': ['-updated_at', '-id']},
        ),
    ]
