# Generated by Django 5.2.14 on 2026-08-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('platform_api', '0037_testcasepackage')]

    operations = [migrations.AddField(model_name='testcasepackage', name='is_locked', field=models.BooleanField(default=False, verbose_name='是否锁定'))]
