# Generated by Django 5.2.16 on 2026-08-11 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_api", "0038_testcasepackage_is_locked"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvironmentPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="环境包名称"
                    ),
                ),
                (
                    "package_type",
                    models.CharField(
                        default="custom", max_length=30, verbose_name="包类型"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "db_table": "aibet_environment_package",
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="environment",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="environments",
                to="platform_api.environmentpackage",
                verbose_name="环境包",
            ),
        ),
    ]
