# Generated by Django 5.2.16 on 2026-08-13 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_api", "0041_environmentpackage_database_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitorScenePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="场景名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_monitor_scene_packages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "db_table": "aibet_monitor_scene_package",
                "db_table_comment": "监控中心场景包表",
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MonitorScenePackageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="执行顺序"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "interface",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitor_scene_package_items",
                        to="platform_api.apiinterface",
                        verbose_name="接口",
                    ),
                ),
                (
                    "scene_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="platform_api.monitorscenepackage",
                        verbose_name="场景包",
                    ),
                ),
            ],
            options={
                "db_table": "aibet_monitor_scene_package_item",
                "db_table_comment": "监控中心场景包接口顺序表",
                "ordering": ["sort_order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scene_package", "interface"),
                        name="uniq_monitor_scene_package_interface",
                    ),
                    models.UniqueConstraint(
                        fields=("scene_package", "sort_order"),
                        name="uniq_monitor_scene_package_order",
                    ),
                ],
            },
        ),
    ]
