import axios from 'axios'
import { clearAuth, auth } from './auth'
import router from './router'
import type { AccountAddResult, AccountBalanceResult, ApiInterface, ApiResponse, AutomationModule, AutomationTask, AutomationTaskResult, DashboardStats, DataFactoryExecution, Environment, EnvironmentAccountSettings, LoginResult, MonitorAlarm, MonitorApiConfig, MonitorExecution, MonitorExecutionDetail, MonitorTask, OrderResultPushResult, PageResult, Role, User } from './types'

const request = axios.create({ baseURL:'/api', timeout:15000 })
request.interceptors.request.use(config => { if (auth.token) config.headers.Authorization = `Bearer ${auth.token}`; return config })
request.interceptors.response.use(response => response.data, error => {
  if (error.response?.status === 401) { clearAuth(); if (router.currentRoute.value.path !== '/login') void router.push('/login') }
  return Promise.reject(new Error(error.response?.data?.message || error.message || '请求失败'))
})

export const login = (data:{username:string;password:string}) => request.post<never,ApiResponse<LoginResult>>('/auth/login/', data)
export const getMe = () => request.get<never,ApiResponse<User>>('/auth/me/')
export const getMyEnvironmentAccounts = () => request.get<never,ApiResponse<EnvironmentAccountSettings>>('/me/environment-accounts/')
export const saveMyEnvironmentAccounts = (accounts:{environment_id:number;account:string}[]) => request.put<never,ApiResponse<EnvironmentAccountSettings>>('/me/environment-accounts/', {accounts})
export const getDashboard = () => request.get<never,ApiResponse<DashboardStats>>('/dashboard/')
export const executeAccountBalance = (data:{environment:number;email:string;amount:number}) => request.post<never,ApiResponse<AccountBalanceResult>>('/data-factory/account-balance/',data)
export const executeAccountAdd = (data:{frontend_environment:number;backend_environment:number;email:string;amount:number|null;quantity:number}) => request.post<never,ApiResponse<AccountAddResult>>('/data-factory/account-add/',data)
export const pushOrderResult = (data:Record<string,string|number>) => request.post<never,ApiResponse<OrderResultPushResult>>('/data-factory/order-result-push/',data)
export const cancelBet = (data:{product:string|number;event_id:string;market_id:string|number;specifiers?:string;start_time?:string;end_time?:string;timestamp?:number|string}) => request.post<never,ApiResponse<OrderResultPushResult>>('/data-factory/bet-cancel/',data)
export const rollbackBetCancel = (data:{product:string|number;event_id:string;market_id:string|number;specifiers?:string;start_time?:string;end_time?:string;timestamp?:number|string}) => request.post<never,ApiResponse<OrderResultPushResult>>('/data-factory/rollback-bet-cancel/',data)
export const rollbackSettlement = (data:Record<string,string|number>) => request.post<never,ApiResponse<OrderResultPushResult>>('/data-factory/rollback-settlement/',data)
export const getDataFactoryEnvironments = () => request.get<never,ApiResponse<Environment[]>>('/data-factory/environments/')
export const getDataFactoryExecutions = (params:Record<string,unknown>) => request.get<never,ApiResponse<PageResult<DataFactoryExecution>>>('/data-factory/executions/',{params})
export const getUsers = (params:Record<string,unknown>) => request.get<never,ApiResponse<PageResult<User>>>('/users/', {params})
export const createUser = (data:Record<string,unknown>) => request.post<never,ApiResponse<User>>('/users/', data)
export const updateUser = (id:number,data:Record<string,unknown>) => request.patch<never,ApiResponse<User>>(`/users/${id}/`,data)
export const toggleUserStatus = (id:number,isActive:boolean) => request.post<never,ApiResponse<User>>(`/users/${id}/toggle-status/`,{is_active:isActive})
export const deleteUser = (id:number) => request.delete<never,ApiResponse<null>>(`/users/${id}/`)
export const changePassword = (id:number,newPassword:string) => request.post<never,ApiResponse<null>>(`/users/${id}/reset-password/`,{new_password:newPassword})
export const getRoles = (params:Record<string,unknown>={}) => request.get<never,ApiResponse<PageResult<Role>>>('/roles/',{params})
export const createRole = (data:Record<string,unknown>) => request.post<never,ApiResponse<Role>>('/roles/',data)
export const updateRole = (id:number,data:Record<string,unknown>) => request.patch<never,ApiResponse<Role>>(`/roles/${id}/`,data)
export const deleteRole = (id:number) => request.delete<never,ApiResponse<null>>(`/roles/${id}/`)
export const savePermissions = (id:number,permissions:string[]) => request.post<never,ApiResponse<Role>>(`/roles/${id}/permissions/`,{permissions})
export const getEnvironments = () => request.get<never,ApiResponse<Environment[]>|Environment[]>('/environments/')
export const createEnvironment = (data:Record<string,unknown>) => request.post<never,ApiResponse<Environment>>('/environments/',data)
export const updateEnvironment = (id:number,data:Record<string,unknown>) => request.patch<never,ApiResponse<Environment>>(`/environments/${id}/`,data)
export const deleteEnvironment = (id:number) => request.delete<never,ApiResponse<null>>(`/environments/${id}/`)
export const copyEnvironment = (id:number) => request.post<never,ApiResponse<Environment>>(`/environments/${id}/copy/`,{})
export const setDefaultEnvironment = (id:number) => request.post<never,ApiResponse<Environment>>(`/environments/${id}/default/`,{})
export const getAutomationModules = (params:Record<string,unknown>={}) => request.get<never,ApiResponse<AutomationModule[]>>('/automation/modules/',{params})
export const getInterfaces = (params:Record<string,unknown>={}) => request.get<never,ApiResponse<PageResult<ApiInterface>>>('/interfaces/',{params})
export const batchImportInterfaces = (data:{text:string;module_name?:string}) => request.post<never,ApiResponse<{imported:{id:number;name:string}[];skipped:{name:string;message:string}[];failed:{name:string;message:string}[];total:number}>>('/interfaces/batch-import/',data)
export const createInterface = (data:Record<string,unknown>) => request.post<never,ApiResponse<ApiInterface>>('/interfaces/',data)
export const updateInterface = (id:number,data:Record<string,unknown>) => request.patch<never,ApiResponse<ApiInterface>>(`/interfaces/${id}/`,data)
export const deleteInterface = (id:number) => request.delete<never,ApiResponse<null>>(`/interfaces/${id}/`)
export const getAutomationTasks = (params:Record<string,unknown>={}) => request.get<never,ApiResponse<PageResult<AutomationTask>>>('/automation/tasks/',{params})
export const getAutomationTask = (id:number) => request.get<never,AutomationTask>(`/automation/tasks/${id}/`)
export const createAutomationTask = (data:Record<string,unknown>) => request.post<never,ApiResponse<AutomationTask>>('/automation/tasks/',data)
export const deleteAutomationTask = (id:number) => request.delete<never,ApiResponse<null>>(`/automation/tasks/${id}/`)
export const runAutomationTask = (id:number,loginPassword:string) => request.post<never,ApiResponse<AutomationTask>>(`/automation/tasks/${id}/run/`,{login_password:loginPassword})
export const stopAutomationTask = (id:number) => request.post<never,ApiResponse<AutomationTask>>(`/automation/tasks/${id}/stop/`,{})
export const retryAutomationTaskResult = (id:number, login_password:string) => request.post<never,ApiResponse<AutomationTaskResult>>(`/automation/task-results/${id}/retry/`,{login_password})
export const getMonitorInterfaces = (params:Record<string,unknown>={}) => request.get<never,ApiResponse<PageResult<MonitorApiConfig>>>('/monitor/interfaces/',{params})
export const createMonitorInterface = (data:Record<string,unknown>) => request.post<never,ApiResponse<MonitorApiConfig>>('/monitor/interfaces/',data)
export const updateMonitorInterface = (id:number,data:Record<string,unknown>) => request.patch<never,ApiResponse<MonitorApiConfig>>(`/monitor/interfaces/${id}/`,data)
export const deleteMonitorInterface = (id:number) => request.delete<never,ApiResponse<null>>(`/monitor/interfaces/${id}/`)
export const toggleMonitorInterface = (id:number,enabled:boolean) => request.post<never,ApiResponse<MonitorApiConfig>>(`/monitor/interfaces/${id}/toggle/`,{enabled})
export const getMonitorTasks = (params:Record<string,unknown>={}) => request.get<never,ApiResponse<PageResult<MonitorTask>>>('/monitor/tasks/',{params})
export const createMonitorTask = (data:Record<string,unknown>) => request.post<never,ApiResponse<MonitorTask>>('/monitor/tasks/',data)
export const updateMonitorTask = (id:number,data:Record<string,unknown>) => request.patch<never,ApiResponse<MonitorTask>>(`/monitor/tasks/${id}/`,data)
export const deleteMonitorTask = (id:number) => request.delete<never,ApiResponse<null>>(`/monitor/tasks/${id}/`)
export const toggleMonitorTask = (id:number,enabled:boolean) => request.post<never,ApiResponse<MonitorTask>>(`/monitor/tasks/${id}/toggle/`,{enabled})
export const runMonitorTask = (id:number) => request.post<never,ApiResponse<MonitorExecution>>(`/monitor/tasks/${id}/run/`,{})
export const getMonitorTaskHistory = (id:number,params:Record<string,unknown>={}) => request.get<never,ApiResponse<PageResult<MonitorExecution>>>(`/monitor/tasks/${id}/history/`,{params})
export const getMonitorExecutions = (params:Record<string,unknown>={}) => request.get<never,ApiResponse<PageResult<MonitorExecution>>>('/monitor/executions/',{params})
export const retryMonitorExecutionDetail = (id:number) => request.post<never,ApiResponse<MonitorExecutionDetail>>(`/monitor/execution-details/${id}/retry/`,{})
export const getMonitorAlarms = (params:Record<string,unknown>={}) => request.get<never,ApiResponse<PageResult<MonitorAlarm>>>('/monitor/alarms/',{params})
export const updateMonitorAlarm = (id:number,data:Record<string,unknown>) => request.patch<never,ApiResponse<MonitorAlarm>>(`/monitor/alarms/${id}/`,data)
