<template>
  <div><section class="surface automation-workspace"><div class="automation-primary-tabs"><div class="automation-tab-options" role="tablist"><button v-for="tab in appTabs" :key="tab.key" :class="{active:activeApp===tab.key}" @click="selectApp(tab.key)"><el-icon><component :is="tab.icon"/></el-icon><span>{{tab.label}}</span><small>{{countByApp(tab.key)}}</small></button></div><el-button class="create-task-button" type="primary" @click="openCreate"><el-icon><Plus/></el-icon>新建执行</el-button></div><div class="automation-list-head"><div><strong>{{activeAppLabel}}自动化任务</strong><span>按创建时间倒序展示</span></div><span>共 {{taskRows.length}} 个任务</span></div><el-table v-loading="loading" :data="taskRows" empty-text="当前暂无任务"><el-table-column prop="name" label="任务名称" min-width="190"/><el-table-column label="业务模块" min-width="150"><template #default="{row}">{{formatModules(row.module_names)}}</template></el-table-column><el-table-column prop="task_type_name" label="类型" width="100"/><el-table-column prop="environment_name" label="环境" width="110"/><el-table-column prop="interface_count" label="接口数量" width="90"/><el-table-column prop="failure_count" label="失败数量" width="90"><template #default="{row}"><span :class="{'failure-count':row.failure_count>0}">{{row.failure_count}}</span></template></el-table-column><el-table-column label="结果" width="100"><template #default="{row}"><el-tag :type="statusType(row.status)">{{row.status_name}}</el-tag></template></el-table-column><el-table-column label="通知" width="100"><template #default="{row}"><el-tooltip :content="row.notification_message" placement="top"><el-tag :type="notificationStatusType(row.notification_status)" size="small">{{notificationStatusName(row.notification_status)}}</el-tag></el-tooltip></template></el-table-column><el-table-column prop="schedule" label="执行策略" min-width="110"/><el-table-column prop="owner_name" label="负责人" width="100"/><el-table-column label="创建时间" width="150"><template #default="{row}">{{formatTime(row.created_at)}}</template></el-table-column><el-table-column label="操作" width="120" fixed="right"><template #default="{row}"><el-button link type="primary" @click="showDetail(row)">详情</el-button><el-button link type="danger" @click="removeTask(row)">删除</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="taskQuery.page" v-model:page-size="taskQuery.pageSize" :page-sizes="pageSizes" :total="total" layout="total, sizes, prev, pager, next" @current-change="loadTasks" @size-change="changePageSize"/></section>
  <el-dialog v-model="dialog" title="新建自动化任务" width="560"><el-form ref="formRef" :model="newTask" :rules="rules" label-position="top"><el-form-item label="任务名称" prop="name"><el-input v-model="newTask.name"/></el-form-item><el-row :gutter="16"><el-col :span="12"><el-form-item label="所属端"><el-select v-model="newTask.app" @change="syncModule"><el-option label="前端" value="frontend"/><el-option label="后台" value="backend"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="业务模块" prop="modules"><el-select v-model="newTask.modules" multiple collapse-tags collapse-tags-tooltip><el-option v-for="item in formModules" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item></el-col></el-row><el-row :gutter="16"><el-col :span="12"><el-form-item label="测试类型" prop="task_type"><el-select v-model="newTask.task_type" @change="setDefaultTaskName"><el-option v-for="item in taskTypes" :key="item.value" :label="item.label" :value="item.value"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="运行环境" prop="environment"><el-select v-model="newTask.environment"><el-option v-for="env in environments" :key="env.id" :label="env.name" :value="env.id"/></el-select></el-form-item></el-col></el-row><el-form-item label="目标系统登录密码" prop="login_password"><el-input v-model="newTask.login_password" type="password" show-password autocomplete="off"/></el-form-item><el-form-item label="执行策略"><el-input v-model="newTask.schedule"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="create">创建任务</el-button></template></el-dialog>
  <el-drawer v-model="detailVisible" title="任务详情" size="min(940px, 94vw)"><template v-if="currentTask"><div class="execution-summary execution-summary-clickable"><button :class="{active:detailFilter==='all'}" @click="setDetailFilter('all')"><span>总接口数</span><b>{{detailStats.total}}</b></button><button :class="{active:detailFilter==='failed'}" @click="setDetailFilter('failed')"><span>失败数量</span><b class="danger-text">{{detailStats.failed}}</b></button><button :class="{active:detailFilter==='timeout'}" @click="setDetailFilter('timeout')"><span>超时数量</span><b class="danger-text">{{detailStats.timeout}}</b></button><button :class="{active:detailFilter==='exception'}" @click="setDetailFilter('exception')"><span>接口异常数量</span><b class="danger-text">{{detailStats.exception}}</b></button></div><div class="execution-detail-head"><strong>接口执行明细</strong><span>共 {{currentTask.execution_details.length}} 个接口</span></div><el-table :data="filteredDetails" empty-text="暂无接口执行明细" max-height="520"><el-table-column prop="interface_name" label="接口名称" min-width="140"/><el-table-column label="方法" width="82"><template #default="{row}"><el-tag effect="plain" size="small">{{row.method}}</el-tag></template></el-table-column><el-table-column prop="path" label="请求路径" min-width="180"><template #default="{row}"><code>{{row.path}}</code></template></el-table-column><el-table-column label="结果" width="90"><template #default="{row}"><el-tag :type="statusType(row.status)" size="small">{{row.status_name}}</el-tag></template></el-table-column><el-table-column label="耗时" width="90"><template #default="{row}">{{formatDuration(row.duration_ms)}}</template></el-table-column><el-table-column label="执行时间" width="150"><template #default="{row}">{{row.executed_at?formatTime(row.executed_at):'-'}}</template></el-table-column><el-table-column prop="response_message" label="执行信息" min-width="140" show-overflow-tooltip/><el-table-column label="操作" width="150" fixed="right"><template #default="{row}"><el-button :disabled="row.status !== 'failed'" link type="warning" @click="showLog(row)">日志</el-button><el-button link type="primary" :loading="retryingId===row.id" @click="retryDetail(row.id)">重试</el-button></template></el-table-column></el-table></template></el-drawer><el-dialog v-model="logVisible" :title="`执行日志 - ${currentLogName}`" width="720"><section class="execution-log-section"><h3>实际请求</h3><pre class="execution-log">{{currentRequestParams}}</pre></section><section class="execution-log-section"><h3>接口返回信息</h3><pre class="execution-log">{{currentLog}}</pre></section></el-dialog></div>
</template>
<script setup lang="ts">
import { computed,onMounted,onUnmounted,reactive,ref } from 'vue';import { ElMessage,ElMessageBox,type FormInstance,type FormRules } from 'element-plus';import { DataBoard,Monitor } from '@element-plus/icons-vue';import { auth } from '@/auth';import * as api from '@/api';import { installOverflowTooltip } from '@/overflowTooltip';import type { AutomationApp,AutomationModule,AutomationTask,AutomationTaskResult,Environment } from '@/types'
import dayjs from 'dayjs'
type AutomationTaskRow=AutomationTask&{task_ids:number[]}
const appTabs=[{key:'frontend' as AutomationApp,label:'前端',icon:Monitor},{key:'backend' as AutomationApp,label:'后台',icon:DataBoard}],taskTypes=[{label:'接口测试',value:'api'},{label:'UI 测试',value:'ui'},{label:'场景测试',value:'scenario'}],pageSizes=[10,50,100]
const taskModuleNames:Record<AutomationApp,string[]>={frontend:['首页','个人中心','赛事','游戏','活动'],backend:['后台']}
const modules=ref<AutomationModule[]>([]),tasks=ref<AutomationTask[]>([]),environments=ref<Environment[]>([]),activeApp=ref<AutomationApp>('frontend'),total=ref(0),loading=ref(false),saving=ref(false),retryingId=ref(0),dialog=ref(false),detailVisible=ref(false),logVisible=ref(false),currentLog=ref(''),currentRequestParams=ref(''),currentLogName=ref(''),detailFilter=ref<'all'|'failed'|'timeout'|'exception'>('all'),currentTask=ref<AutomationTask|null>(null),formRef=ref<FormInstance>()
const taskQuery=reactive({page:1,pageSize:10})
const newTask=reactive({name:'',app:'frontend' as AutomationApp,modules:[] as number[],task_type:'api',environment:0,schedule:'手动执行',login_password:''})
const rules:FormRules={name:[{required:true,message:'请输入任务名称'}],modules:[{type:'array',required:true,message:'请选择业务模块'}],task_type:[{required:true,message:'请选择测试类型'}],environment:[{required:true,message:'请选择运行环境'}],login_password:[{required:true,message:'请输入目标系统登录密码'}]}
const formModules=computed(()=>taskModuleNames[newTask.app].map(name=>modules.value.find(item=>item.app===newTask.app&&item.name===name)).filter((item):item is AutomationModule=>Boolean(item))),activeAppLabel=computed(()=>appTabs.find(item=>item.key===activeApp.value)?.label||'')
const taskRows=computed<AutomationTaskRow[]>(()=>Array.isArray(tasks.value)?tasks.value.map(task=>({...task,module_names:task.module_names?.length?task.module_names:task.module_name?[task.module_name]:[],task_ids:[task.id]})):[])
const detailRows=computed(()=>Array.isArray(currentTask.value?.execution_details)?currentTask.value?.execution_details||[]:[])
const filteredDetails=computed(()=>detailRows.value.filter(item=>detailFilter.value==='all'||(detailFilter.value==='failed'&&item.status==='failed')||(detailFilter.value==='timeout'&&isTimeout(item))||(detailFilter.value==='exception'&&isException(item))))
const detailStats=computed(()=>({total:detailRows.value.length,failed:detailRows.value.filter(item=>item.status==='failed').length,timeout:detailRows.value.filter(isTimeout).length,exception:detailRows.value.filter(isException).length}))
function countByApp(app:AutomationApp){return (Array.isArray(modules.value)?modules.value:[]).filter(item=>item.app===app).reduce((sum,item)=>sum+item.task_count,0)}
async function loadModules(){const res=await api.getAutomationModules();modules.value=Array.isArray(res.data)?res.data:[]}
async function loadTasks(){loading.value=true;try{const res=await api.getAutomationTasks({app:activeApp.value,page:taskQuery.page,pageSize:taskQuery.pageSize});const page=res.data||{list:[],total:0};tasks.value=Array.isArray(page.list)?page.list:[];total.value=Number(page.total)||0}catch(e){tasks.value=[];total.value=0;ElMessage.error((e as Error).message)}finally{loading.value=false}}
async function selectApp(app:AutomationApp){activeApp.value=app;taskQuery.page=1;await loadTasks()}
function changePageSize(){taskQuery.page=1;void loadTasks()}
function syncModule(){newTask.modules=formModules.value[0]?.id?[formModules.value[0].id]:[]}
function setDefaultTaskName(){const typeName=taskTypes.find(item=>item.value===newTask.task_type)?.label||'';const userName=auth.user?.name||auth.user?.username||'用户';newTask.name=`${typeName}-${userName}-${dayjs().format('HHmmss')}`}
function isTimeout(detail:AutomationTaskResult){return detail.status==='failed'&&/超时|timeout/i.test(`${detail.response_message} ${detail.response_log}`)}
function isException(detail:AutomationTaskResult){return detail.status==='failed'&&!isTimeout(detail)}
function setDetailFilter(value:'all'|'failed'|'timeout'|'exception'){detailFilter.value=value}
function showLog(detail:AutomationTaskResult){const headers=Object.fromEntries(Object.entries(detail.headers||{}).map(([key,value])=>/authorization|x-token/i.test(key)?[key,'***']:[key,value]));currentLogName.value=detail.interface_name;currentRequestParams.value=JSON.stringify({method:detail.method,url:detail.path,headers,params:detail.request_params||{}},null,2);currentLog.value=detail.response_log||detail.response_message;logVisible.value=true}
function openCreate(){newTask.app=activeApp.value;syncModule();newTask.environment=(environments.value.find(item=>item.is_default)||environments.value[0])?.id||0;setDefaultTaskName();dialog.value=true}
async function create(){if(!await formRef.value?.validate().catch(()=>false))return;saving.value=true;try{await api.createAutomationTask({name:newTask.name.trim(),module_ids:newTask.modules,task_type:newTask.task_type,environment:newTask.environment,status:'pending',schedule:newTask.schedule,owner:auth.user?.id,login_password:newTask.login_password.trim()});dialog.value=false;activeApp.value=newTask.app;taskQuery.page=1;newTask.name='';newTask.login_password='';newTask.modules=[];await Promise.all([loadModules(),loadTasks()]);ElMessage.success('任务已创建，正在执行')}catch(e){ElMessage.error((e as Error).message)}finally{saving.value=false}}
async function showDetail(task:AutomationTask|AutomationTaskRow){detailFilter.value='all';detailVisible.value=true;currentTask.value=task;try{const refreshed=await api.getAutomationTask(task.id);currentTask.value=refreshed}catch(e){detailVisible.value=false;ElMessage.error((e as Error).message)}}function statusType(status:string){return status==='passed'?'success':status==='running'?'primary':status==='failed'?'danger':'info'}function notificationStatusType(status:string){return status==='sent'?'success':status==='failed'?'danger':status==='disabled'?'info':'warning'}function notificationStatusName(status:string){return status==='sent'?'已发送':status==='failed'?'发送失败':status==='disabled'?'未配置':'待发送'}
async function retryDetail(id:number){if(!currentTask.value)return;const taskId=currentTask.value.id;let password='';try{const prompt=await ElMessageBox.prompt('重试将先登录并执行关联接口，再执行当前接口。请输入目标系统登录密码','接口重试',{inputType:'password',confirmButtonText:'开始重试',cancelButtonText:'取消',inputValidator:value=>String(value??'').trim()?true:'请输入密码'});password=String(prompt.value??'').trim()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error)?.message||'打开重试确认框失败');return}retryingId.value=id;try{await api.retryAutomationTaskResult(id,password);await loadTasks();const groupedTask=taskRows.value.find(item=>item.task_ids.includes(taskId));if(groupedTask)await showDetail(groupedTask);else{const refreshed=await api.getAutomationTask(taskId);currentTask.value=refreshed}ElMessage.success('接口及关联链路重试完成')}catch(e){ElMessage.error((e as Error).message)}finally{retryingId.value=0}}
async function removeTask(task:AutomationTask|AutomationTaskRow){try{await ElMessageBox.confirm(`确定删除任务“${task.name}”吗？任务执行明细也会一并删除。`,'删除任务',{type:'warning'});await api.deleteAutomationTask(task.id);if(taskRows.value.length===1&&taskQuery.page>1)taskQuery.page-=1;await Promise.all([loadModules(),loadTasks()]);ElMessage.success('任务已删除')}catch(e){if(e!=='cancel')ElMessage.error((e as Error).message)}}
function formatDuration(value:number|null){return value===null?'-':`${value} ms`}function formatTime(value:string){return dayjs(value).format('YYYY-MM-DD HH:mm:ss')}
function formatModules(value:string[]){return [...new Set(value)].join('、')}
let removeOverflowTooltip=()=>{}
onMounted(async()=>{removeOverflowTooltip=installOverflowTooltip();try{const envRes=await api.getEnvironments();environments.value=Array.isArray(envRes)?envRes:envRes.data;await loadModules();await loadTasks()}catch(e){ElMessage.error((e as Error).message)}})
onUnmounted(()=>removeOverflowTooltip())
</script>
