<template>
  <main class="login-page"><section class="login-aside"><div class="login-brand"><span>A</span><b>AIBET Auto</b></div><div><small>AI TEST AUTOMATION</small><h1>让每一次发布<br>都有据可依</h1><p>统一管理自动化任务、环境配置与平台权限，持续交付更可靠的软件。</p></div><div class="login-stats"><div><b>96.4%</b><span>整体通过率</span></div><div><b>128</b><span>今日执行</span></div><div><b>92</b><span>质量评分</span></div></div></section><section class="login-form-wrap"><el-form ref="formRef" :model="form" :rules="rules" class="login-form" @submit.prevent="submit"><div class="mobile-brand">AIBET Auto</div><h2>欢迎回来</h2><p>登录智能自动化测试平台</p><el-form-item prop="username"><label>登录账号</label><el-input v-model="form.username" size="large" prefix-icon="User" placeholder="请输入账号" /></el-form-item><el-form-item prop="password"><label>登录密码</label><el-input v-model="form.password" size="large" prefix-icon="Lock" type="password" show-password placeholder="请输入密码" @keyup.enter="submit" /></el-form-item><el-button type="primary" size="large" :loading="loading" native-type="submit">登录平台</el-button><div class="demo-tip">演示账号：<code>admin</code> / <code>Aibet@123456</code></div></el-form></section></main>
</template>
<script setup lang="ts">
import { reactive,ref } from 'vue';import { useRouter } from 'vue-router';import { ElMessage,type FormInstance,type FormRules } from 'element-plus';import { login } from '@/api';import { setAuth } from '@/auth'
const router=useRouter(),formRef=ref<FormInstance>(),loading=ref(false),form=reactive({username:'admin',password:'Aibet@123456'})
const rules:FormRules={username:[{required:true,message:'请输入登录账号'}],password:[{required:true,message:'请输入登录密码'}]}
async function submit(){if(!await formRef.value?.validate().catch(()=>false))return;loading.value=true;try{const res=await login(form);setAuth(res.data.access,res.data.refresh,res.data.user);ElMessage.success('登录成功');await router.push('/')}catch(error){ElMessage.error((error as Error).message)}finally{loading.value=false}}
</script>
