<template>
  <div><section class="surface setting-main">
    <template v-if="active==='environment'">
      <div class="section-head bordered"><div><h3>环境配置包</h3><p>按环境包管理多个前台、后台或其他环境配置。</p></div><el-button v-if="hasPermission('environment.manage')" type="primary" plain @click="openPackage()"><el-icon><Plus/></el-icon>新增环境包</el-button></div>
      <div class="env-list"><article v-for="pkg in environmentPackages" :key="pkg.id" class="env-row"><span class="env-symbol">{{pkg.name.slice(0,1)}}</span><div style="flex:1"><h4>{{pkg.name}}</h4><p>{{pkg.description||'暂无描述'}}　共 {{pkg.environments.length}} 个环境配置</p><div v-for="env in pkg.environments" :key="env.id" class="package-env"><b>{{env.name}}</b><small>{{env.base_url}}</small><span v-if="hasPermission('environment.manage')"><el-button link type="primary" @click="openEnvironment(env,pkg)">编辑</el-button><el-button link type="danger" @click="removeEnv(env)">删除</el-button></span></div></div><div v-if="hasPermission('environment.manage')" class="row-actions"><el-button link type="primary" @click="openEnvironment(undefined,pkg)">添加配置</el-button><el-button link type="primary" @click="openPackage(pkg)">编辑包</el-button><el-button link type="danger" @click="removePackage(pkg)">删除包</el-button></div></article></div>
    </template>
    <template v-if="active==='users'">
      <div class="section-head bordered"><div><h3>用户管理</h3><p>维护平台成员账号、角色与启用状态。</p></div><el-button v-if="hasPermission('users.manage')" type="primary" plain @click="openUser()"><el-icon><Plus/></el-icon>新建用户</el-button></div>
      <div class="table-tools"><el-input v-model="userQuery.keyword" clearable prefix-icon="Search" placeholder="搜索姓名、账号或邮箱" @input="loadUsers"/><el-select v-model="userQuery.role" clearable placeholder="全部角色" @change="loadUsers"><el-option v-for="role in roles" :key="role.code" :label="role.name" :value="role.code"/></el-select><span>共 {{userTotal}} 位用户</span></div>
      <el-table v-loading="loading" :data="users"><el-table-column label="用户" min-width="130"><template #default="{row}"><div class="person"><el-avatar :size="30">{{row.name.slice(0,1)}}</el-avatar><b>{{row.name}}</b></div></template></el-table-column><el-table-column prop="username" label="登录账号"/><el-table-column prop="email" label="邮箱" min-width="180"/><el-table-column prop="role_name" label="角色"><template #default="{row}"><el-tag type="info">{{row.role_name}}</el-tag></template></el-table-column><el-table-column label="状态"><template #default="{row}"><el-switch :model-value="row.is_active" :disabled="!hasPermission('users.status')" @change="toggleUser(row,$event)"/></template></el-table-column><el-table-column label="操作" width="210"><template #default="{row}"><el-button v-if="hasPermission('users.manage')" link type="primary" @click="openUser(row)">编辑</el-button><el-button v-if="hasPermission('users.manage')" link type="primary" @click="changePassword(row)">修改密码</el-button><el-button v-if="hasPermission('users.delete')" link type="danger" :disabled="row.role==='admin'" @click="removeUser(row)">删除</el-button></template></el-table-column></el-table>
      <el-pagination v-model:current-page="userQuery.page" :total="userTotal" :page-size="10" layout="total, prev, pager, next" @current-change="loadUsers"/>
    </template>
    <template v-if="active==='roles'">
      <div class="section-head bordered"><div><h3>角色管理</h3><p>定义角色信息，并按模块分配访问权限。</p></div><el-button v-if="hasPermission('roles.manage')" type="primary" plain @click="openRole()"><el-icon><Plus/></el-icon>新建角色</el-button></div>
      <div class="table-tools"><el-input v-model="roleKeyword" clearable prefix-icon="Search" placeholder="搜索角色名称或编码" @input="loadRoles"/><span>共 {{roleTotal}} 个角色</span></div>
      <el-table v-loading="loading" :data="roles"><el-table-column label="角色名称"><template #default="{row}"><b>{{row.name}}</b> <el-tag v-if="row.is_system" size="small">系统</el-tag></template></el-table-column><el-table-column prop="code" label="角色编码"/><el-table-column prop="description" label="描述" min-width="180"/><el-table-column prop="user_count" label="用户数"/><el-table-column label="操作" width="210"><template #default="{row}"><el-button v-if="hasPermission('roles.manage')" link type="primary" @click="openRole(row)">编辑</el-button><el-button v-if="row.code!=='admin'&&hasPermission('roles.grant')" link type="primary" @click="openPermission(row)">权限配置</el-button><el-button v-if="hasPermission('roles.delete')" link type="danger" :disabled="row.is_system||row.user_count>0" @click="removeRole(row)">删除</el-button></template></el-table-column></el-table>
    </template>
<el-dialog v-model="packageDialog" :title="packageForm.id?'编辑环境包':'新增环境包'" width="520"><el-form :model="packageForm" label-position="top"><el-form-item label="包名称"><el-input v-model="packageForm.name"/></el-form-item><el-form-item label="描述"><el-input v-model="packageForm.description" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="packageDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="savePackage">保存</el-button></template></el-dialog>
  </section>

  <el-dialog v-model="envDialog" :title="envForm.id?'编辑环境':'添加环境'" width="620"><el-form ref="envFormRef" :model="envForm" :rules="envRules" label-position="top"><el-form-item label="所属环境包"><el-select v-model="envForm.package" placeholder="请选择环境包" clearable><el-option v-for="pkg in environmentPackages" :key="pkg.id" :label="pkg.name" :value="pkg.id"/></el-select></el-form-item><el-row :gutter="16"><el-col :span="12"><el-form-item label="环境名称" prop="name"><el-input v-model="envForm.name"/></el-form-item></el-col><el-col :span="12"><el-form-item label="服务地址" prop="base_url"><el-input v-model="envForm.base_url" placeholder="https://"/></el-form-item></el-col></el-row><el-form-item label="登录地址"><el-input v-model="envForm.login_url" placeholder="可选"/></el-form-item><el-form-item label="描述"><el-input v-model="envForm.description"/></el-form-item><el-form-item label="环境变量"><div class="variable-list"><div v-for="(variable,index) in envForm.variables" :key="index"><el-input v-model="variable.key" placeholder="变量名"/><el-input v-model="variable.value" placeholder="变量值"/><el-button circle text type="danger" @click="envForm.variables.splice(index,1)"><el-icon><Delete/></el-icon></el-button></div><el-button link type="primary" @click="envForm.variables.push({key:'',value:''})"><el-icon><Plus/></el-icon>添加变量</el-button></div></el-form-item><el-checkbox v-model="envForm.is_default">设为默认环境</el-checkbox></el-form><template #footer><el-button @click="envDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveEnvironment">保存</el-button></template></el-dialog>
  <el-dialog v-model="userDialog" :title="userForm.id?'编辑用户':'新建用户'" width="520"><el-form ref="userFormRef" :model="userForm" :rules="userRules" label-position="top"><el-row :gutter="16"><el-col :span="12"><el-form-item label="姓名" prop="name"><el-input v-model="userForm.name"/></el-form-item></el-col><el-col :span="12"><el-form-item label="登录账号" prop="username"><el-input v-model="userForm.username" :disabled="Boolean(userForm.id)"/></el-form-item></el-col></el-row><el-form-item label="邮箱（选填）" prop="email"><el-input v-model="userForm.email"/></el-form-item><el-form-item v-if="!userForm.id" label="初始密码" prop="password"><el-input v-model="userForm.password" type="password" show-password/></el-form-item><el-form-item label="角色" prop="role"><el-select v-model="userForm.role"><el-option v-for="role in roles" :key="role.code" :label="role.name" :value="role.code"/></el-select></el-form-item></el-form><template #footer><el-button @click="userDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveUser">保存</el-button></template></el-dialog>
  <el-dialog v-model="roleDialog" :title="roleForm.id?'编辑角色':'新建角色'" width="520"><el-form ref="roleFormRef" :model="roleForm" :rules="roleRules" label-position="top"><el-form-item label="角色名称" prop="name"><el-input v-model="roleForm.name"/></el-form-item><el-form-item label="角色编码" prop="code"><el-input v-model="roleForm.code" :disabled="Boolean(roleForm.id)" placeholder="小写字母和下划线"/></el-form-item><el-form-item label="角色描述"><el-input v-model="roleForm.description" type="textarea" :rows="3"/></el-form-item></el-form><template #footer><el-button @click="roleDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveRole">保存</el-button></template></el-dialog>
  <el-dialog v-model="permissionDialog" title="权限配置" width="700"><p class="permission-title">正在配置：<b>{{currentRole?.name}}</b></p><div class="permission-grid"><section v-for="group in permissionGroups" :key="group.name"><h4>{{group.name}}</h4><el-checkbox-group v-model="checkedPermissions"><el-checkbox v-for="item in group.items" :key="item[0]" :value="item[0]">{{item[1]}}</el-checkbox></el-checkbox-group></section></div><template #footer><el-button @click="permissionDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveRolePermissions">保存权限</el-button></template></el-dialog>
  </div>
</template>
<script setup lang="ts">
import { computed,reactive,ref,watch } from 'vue';import { useRoute } from 'vue-router';import { ElMessage,ElMessageBox,type FormInstance,type FormRules } from 'element-plus';import dayjs from 'dayjs';import { hasPermission,updateAuthUser } from '@/auth';import * as api from '@/api';import type { Environment,EnvironmentPackage,EnvironmentVariable,Role,User } from '@/types'
const route=useRoute(),active=computed(()=>route.path.endsWith('/users')?'users':route.path.endsWith('/roles')?'roles':'environment'),loading=ref(false),saving=ref(false)
const environments=ref<Environment[]>([]),environmentPackages=ref<EnvironmentPackage[]>([]),users=ref<User[]>([]),roles=ref<Role[]>([]),userTotal=ref(0),roleTotal=ref(0),roleKeyword=ref(''),userQuery=reactive({keyword:'',role:'',page:1})
const envDialog=ref(false),packageDialog=ref(false),userDialog=ref(false),roleDialog=ref(false),permissionDialog=ref(false),envFormRef=ref<FormInstance>(),userFormRef=ref<FormInstance>(),roleFormRef=ref<FormInstance>()
const envForm=reactive({id:0,name:'',description:'',base_url:'',login_url:'',variables:[] as EnvironmentVariable[],is_default:false,package:null as number|null}),packageForm=reactive({id:0,name:'',description:''}),selectedPackage=ref<EnvironmentPackage|null>(null),userForm=reactive({id:0,name:'',username:'',email:'',password:'',role:''}),roleForm=reactive({id:0,name:'',code:'',description:''})
const currentRole=ref<Role|null>(null),checkedPermissions=ref<string[]>([])
const permissionGroups=[
  {name:'首页',items:[['home.view','查看首页']]},
  {name:'智能工具',items:[['data_factory.view','查看数据工厂'],['data_factory.account_add','账户添加操作'],['data_factory.account_balance','账户余额操作'],['data_factory.member_status_activate','用户状态激活'],['data_factory.member_query','查询用户信息'],['data_factory.order_result_push','订单结果推送'],['data_factory.rollback_settlement','回滚结算操作'],['data_factory.bet_cancel','取消操作'],['data_factory.rollback_bet_cancel','回滚取消操作']]},
  {name:'自动化',items:[['automation.view','查看任务'],['automation.create','创建任务'],['automation.run','执行任务'],['automation.edit','编辑任务'],['automation.delete','删除任务']]},
  {name:'用例管理',items:[['testcase.package.view','查看用例包'],['testcase.package.create','新建或导入用例包'],['testcase.package.edit','编辑用例包'],['testcase.package.delete','删除用例包'],['testcase.execution.view','查看用例执行']]},
  {name:'监控中心',items:[['monitor.api.view','查看监控接口'],['monitor.api.manage','管理监控接口'],['monitor.task.view','查看监控任务'],['monitor.task.manage','管理监控任务'],['monitor.task.run','执行监控任务'],['monitor.alarm.view','查看报警'],['monitor.alarm.handle','处理报警']]},
  {name:'环境配置',items:[['environment.view','查看环境'],['environment.manage','管理环境']]},
  {name:'用户管理',items:[['users.view','查看用户'],['users.manage','管理用户'],['users.status','启用或停用'],['users.delete','删除用户']]},
  {name:'角色管理',items:[['roles.view','查看角色'],['roles.manage','管理角色'],['roles.grant','配置权限'],['roles.delete','删除角色']]},
]
const envRules:FormRules={name:[{required:true,message:'请输入环境名称'}],base_url:[{required:true,message:'请输入服务地址'},{type:'url',message:'请输入有效 URL'}]},userRules:FormRules={name:[{required:true,message:'请输入姓名'}],username:[{required:true,message:'请输入账号'}],email:[{type:'email',message:'邮箱格式不正确'}],password:[{required:true,message:'请输入密码'},{min:6,message:'至少 6 位'}],role:[{required:true,message:'请选择角色'}]},roleRules:FormRules={name:[{required:true,message:'请输入角色名称'}],code:[{required:true,message:'请输入角色编码'},{pattern:/^[a-z_]+$/,message:'只能使用小写字母和下划线'}]}
async function run(job:()=>Promise<void>){loading.value=true;try{await job()}catch(e){ElMessage.error((e as Error).message)}finally{loading.value=false}}
async function loadEnvironments(){await run(async()=>{let packages:EnvironmentPackage[]=[];try{const response=await api.getEnvironmentPackages();packages=(Array.isArray(response)?response:response.data||[]) as EnvironmentPackage[]}catch{packages=[]}if(packages.length){environmentPackages.value=packages;return}const response=await api.getEnvironments();const environments=Array.isArray(response)?response:(response.data as Environment[]);environmentPackages.value=environments.reduce<EnvironmentPackage[]>((groups,env)=>{const key=env.package||0;let group=groups.find(item=>item.id===key);if(!group){group={id:key,name:key?'环境配置包':'未归档环境',package_type:'custom',description:'',environments:[],created_at:''};groups.push(group)}group.environments.push(env);return groups},[])})}
async function loadUsers(){await run(async()=>{const res=await api.getUsers({keyword:userQuery.keyword||undefined,role:userQuery.role||undefined,page:userQuery.page,pageSize:10});users.value=res.data.list;userTotal.value=res.data.total})}
async function loadRoles(){await run(async()=>{const res=await api.getRoles({keyword:roleKeyword.value||undefined,pageSize:100});roles.value=res.data.list;roleTotal.value=res.data.total})}
watch(active,key=>{if(key==='users')void Promise.all([loadRoles(),loadUsers()]);if(key==='roles')void loadRoles();if(key==='environment')void loadEnvironments()},{immediate:true})
function openPackage(pkg?:EnvironmentPackage){Object.assign(packageForm,pkg&&pkg.id>0?{id:pkg.id,name:pkg.name,description:pkg.description}:{id:0,name:pkg?.name||'',description:pkg?.description||''});packageDialog.value=true}
async function savePackage(){const name=packageForm.name.trim();if(!name)return ElMessage.warning('请输入环境包名称');if(environmentPackages.value.some(pkg=>pkg.name.trim()===name&&pkg.id!==packageForm.id))return ElMessage.warning('环境包名称已存在，请更换名称');saving.value=true;try{const payload={name,description:packageForm.description};packageForm.id?await api.updateEnvironmentPackage(packageForm.id,payload):await api.createEnvironmentPackage(payload);packageDialog.value=false;await loadEnvironments();ElMessage.success('环境包保存成功')}catch(e){ElMessage.error((e as Error).message)}finally{saving.value=false}}
async function removePackage(pkg:EnvironmentPackage){if(pkg.id<=0)return;try{await ElMessageBox.confirm(`确定删除环境包“${pkg.name}”吗？`,'删除环境包',{type:'warning'});await api.deleteEnvironmentPackage(pkg.id);await loadEnvironments()}catch(e){if(e!=='cancel')ElMessage.error((e as Error).message)}}
function openEnvironment(env?:Environment,pkg?:EnvironmentPackage){if(!hasPermission('environment.manage'))return;selectedPackage.value=pkg||null;Object.assign(envForm,env?{...env,variables:env.variables.map(v=>({...v}))}:{id:0,name:'',description:'',base_url:'',login_url:'',variables:[],is_default:false,package:pkg?.id||null});envDialog.value=true}
async function saveEnvironment(){if(!hasPermission('environment.manage')||!await envFormRef.value?.validate().catch(()=>false))return;saving.value=true;try{const payload={name:envForm.name,description:envForm.description,base_url:envForm.base_url,login_url:envForm.login_url,variables:envForm.variables.filter(v=>v.key),is_default:envForm.is_default,package:envForm.package};envForm.id?await api.updateEnvironment(envForm.id,payload):await api.createEnvironment(payload);envDialog.value=false;await loadEnvironments();ElMessage.success('环境保存成功')}catch(e){ElMessage.error((e as Error).message)}finally{saving.value=false}}
async function copyEnv(env:Environment){if(!hasPermission('environment.manage'))return;try{await api.copyEnvironment(env.id);await loadEnvironments();ElMessage.success('环境复制成功')}catch(e){ElMessage.error((e as Error).message)}}
async function defaultEnv(env:Environment){if(!hasPermission('environment.manage'))return;try{await api.setDefaultEnvironment(env.id);await loadEnvironments();ElMessage.success('默认环境已更新')}catch(e){ElMessage.error((e as Error).message)}}
async function removeEnv(env:Environment){if(!hasPermission('environment.manage'))return;try{await ElMessageBox.confirm(`确定删除环境“${env.name}”吗？`,'删除环境',{type:'warning'});await api.deleteEnvironment(env.id);await loadEnvironments();ElMessage.success('环境已删除')}catch(e){if(e!=='cancel')ElMessage.error((e as Error).message)}}
function openUser(user?:User){if(!hasPermission('users.manage'))return;Object.assign(userForm,user?{id:user.id,name:user.name,username:user.username,email:user.email,password:'',role:user.role}:{id:0,name:'',username:'',email:'',password:'',role:roles.value[0]?.code||''});userDialog.value=true}
async function saveUser(){if(!hasPermission('users.manage')||!await userFormRef.value?.validate().catch(()=>false))return;saving.value=true;try{const payload={name:userForm.name,email:userForm.email,role:userForm.role,...(!userForm.id?{username:userForm.username,password:userForm.password}:{})};const response=userForm.id?await api.updateUser(userForm.id,payload):await api.createUser(payload);updateAuthUser(response.data);userDialog.value=false;await Promise.all([loadUsers(),loadRoles()]);ElMessage.success('用户保存成功')}catch(e){ElMessage.error((e as Error).message)}finally{saving.value=false}}
async function toggleUser(user:User,value:string|number|boolean){if(!hasPermission('users.status'))return;try{await api.toggleUserStatus(user.id,Boolean(value));await loadUsers();ElMessage.success(`用户已${value?'启用':'停用'}`)}catch(e){ElMessage.error((e as Error).message)}}
async function changePassword(user:User){if(!hasPermission('users.manage'))return;try{const {value}=await ElMessageBox.prompt(`为“${user.name}”设置新密码`,'修改密码',{inputType:'password',inputPattern:/.{6,}/,inputErrorMessage:'密码至少 6 位',confirmButtonText:'保存'});await api.changePassword(user.id,value);ElMessage.success('密码修改成功')}catch(e){if(e!=='cancel')ElMessage.error((e as Error).message)}}
async function removeUser(user:User){if(!hasPermission('users.delete'))return;try{await ElMessageBox.confirm(`确定删除用户“${user.name}”吗？`,'删除用户',{type:'warning'});await api.deleteUser(user.id);await Promise.all([loadUsers(),loadRoles()]);ElMessage.success('用户已删除')}catch(e){if(e!=='cancel')ElMessage.error((e as Error).message)}}
function openRole(role?:Role){if(!hasPermission('roles.manage'))return;Object.assign(roleForm,role?{id:role.id,name:role.name,code:role.code,description:role.description}:{id:0,name:'',code:'',description:''});roleDialog.value=true}
async function saveRole(){if(!hasPermission('roles.manage')||!await roleFormRef.value?.validate().catch(()=>false))return;saving.value=true;try{const payload={name:roleForm.name,code:roleForm.code,description:roleForm.description};roleForm.id?await api.updateRole(roleForm.id,payload):await api.createRole(payload);roleDialog.value=false;await loadRoles();ElMessage.success('角色保存成功')}catch(e){ElMessage.error((e as Error).message)}finally{saving.value=false}}
function openPermission(role:Role){if(!hasPermission('roles.grant'))return;currentRole.value=role;checkedPermissions.value=[...role.permissions];permissionDialog.value=true}
async function saveRolePermissions(){if(!hasPermission('roles.grant')||!currentRole.value)return;saving.value=true;try{await api.savePermissions(currentRole.value.id,checkedPermissions.value);const currentUser=await api.getMe();updateAuthUser(currentUser.data);permissionDialog.value=false;await loadRoles();ElMessage.success('权限保存成功')}catch(e){ElMessage.error((e as Error).message)}finally{saving.value=false}}
async function removeRole(role:Role){if(!hasPermission('roles.delete'))return;try{await ElMessageBox.confirm(`确定删除角色“${role.name}”吗？`,'删除角色',{type:'warning'});await api.deleteRole(role.id);await loadRoles();ElMessage.success('角色已删除')}catch(e){if(e!=='cancel')ElMessage.error((e as Error).message)}}
</script>
