<template>
  <section class="mind-editor">
    <header class="editor-toolbar"><div class="toolbar-left"><el-button @click="back"><el-icon><ArrowLeft/></el-icon>返回</el-button><el-divider direction="vertical"/><el-input v-model="packageName" class="package-name" maxlength="200" show-word-limit/></div><div class="toolbar-center"><el-tooltip content="放大"><el-button circle @click="zoom(0.1)"><el-icon><ZoomIn/></el-icon></el-button></el-tooltip><el-tooltip content="缩小"><el-button circle @click="zoom(-0.1)"><el-icon><ZoomOut/></el-icon></el-button></el-tooltip><el-tooltip content="适应画布"><el-button circle @click="fit"><el-icon><FullScreen/></el-icon></el-button></el-tooltip><el-divider direction="vertical"/><el-button @click="addChild"><el-icon><Plus/></el-icon>新增节点</el-button><el-button :disabled="!activeNode" @click="removeNode"><el-icon><Delete/></el-icon>删除节点</el-button></div><el-button type="primary" :loading="saving" @click="save"><el-icon><Check/></el-icon>保存</el-button></header>
    <div class="editor-body"><div ref="canvas" class="mindmap-container" v-loading="loading"></div><aside v-if="activeNode" class="node-panel"><h4>节点属性</h4><el-form label-position="top"><el-form-item label="节点名称"><el-input v-model="nodeText" @change="updateText"/></el-form-item><el-form-item label="节点标记"><el-select v-model="nodeTag" clearable placeholder="选择标记" @change="updateTag"><el-option label="待定" value="待定"/><el-option label="冒烟" value="冒烟"/><el-option label="废除" value="废除"/></el-select></el-form-item></el-form><el-button text type="primary" @click="clearTag">清除标记</el-button></aside></div>
  </section>
</template>
<script setup lang="ts">
import { nextTick,onBeforeUnmount,onMounted,ref } from 'vue';import { useRoute,useRouter } from 'vue-router';import { ElMessage,ElMessageBox } from 'element-plus';import MindMap from 'simple-mind-map';import Drag from 'simple-mind-map/src/plugins/Drag';import 'simple-mind-map/dist/simpleMindMap.esm.css';import * as api from '@/api';import type { TestCaseNode,TestCasePackage } from '@/types'
type MindNode={data:Record<string,unknown>;children:MindNode[]}
const route=useRoute(),router=useRouter(),canvas=ref<HTMLElement>(),loading=ref(false),saving=ref(false),packageName=ref(''),activeNode=ref<any>(null),nodeText=ref(''),nodeTag=ref('')
let mindMap:any=null;const packageId=String(route.params.id),isNew=packageId==='new',id=Number(packageId);let editingId:number|null=isNew?null:id
MindMap.usePlugin(Drag)
function toMind(node:TestCaseNode):MindNode{const tag=(node as any).tag;return {data:{text:node.title,...(tag?{tag:Array.isArray(tag)?tag:[String(tag)]}:{}),...(node.image?{image:node.image}:{}),...(node.imageSize?{imageSize:node.imageSize}:{})},children:(node.children||[]).map(toMind)}}
function fromMind(node:MindNode):TestCaseNode{const tag=node.data?.tag,image=node.data?.image,imageSize=node.data?.imageSize;return {title:String(node.data?.text||'未命名节点'),children:(node.children||[]).map(fromMind),...(tag?{tag:Array.isArray(tag)?tag.map(String):[String(tag)]}:{}),...(image?{image:String(image)}:{}),...(imageSize&&typeof imageSize==='object'?{imageSize:imageSize as {width?:number;height?:number}}:{})} as TestCaseNode}
function currentContent():TestCaseNode{const raw=mindMap.getData(true);const root=raw?.root|| (Array.isArray(raw)?raw[0]:raw);return fromMind(root?.data?root:{data:{text:'中心主题'},children:[]})}
function selectNode(node:any){activeNode.value=node;nodeText.value=String(node?.getData?.('text')||'');const tag=node?.getData?.('tag');nodeTag.value=Array.isArray(tag)?String(tag[0]||''):String(tag||'')}
async function load(){loading.value=true;try{const item=isNew?{name:'',content:{title:'中心主题',children:[]}}:(await api.getTestCasePackage(id)).data;packageName.value=item.name;mindMap=new MindMap({el:canvas.value,data:toMind(item.content),theme:'classic4',layout:'logicalStructure',mouseScaleCenterUseMousePosition:true,enableFreeDrag:false,beforeTextEdit:(_node:any,isInserting:boolean)=>!isInserting});mindMap.on('node_active',selectNode);mindMap.on('hide_text_edit',()=>{if(activeNode.value)nodeText.value=String(activeNode.value.getData('text')||'')});mindMap.on('node_dragend',()=>ElMessage.success('节点层级已调整，请保存用例包'));mindMap.on('data_change',()=>{});await nextTick();requestAnimationFrame(()=>{const instance=mindMap;if(!instance)return;instance.resize();instance.view.fit();setTimeout(()=>{if(!instance||!instance.el)return;instance.resize();instance.view.reset();const root=instance.renderer?.root;if(root)instance.renderer.moveNodeToCenter(root,false)},120)})}catch(e){ElMessage.error((e as Error).message);void back()}finally{loading.value=false}}
function addChild(){if(mindMap)mindMap.execCommand('INSERT_CHILD_NODE')}
async function removeNode(){if(!mindMap||!activeNode.value)return;try{await ElMessageBox.confirm('确定删除当前节点及其子节点吗？','删除节点',{type:'warning'});mindMap.execCommand('REMOVE_NODE');activeNode.value=null}catch(e){if(e!=='cancel')ElMessage.error((e as Error).message)}}
function updateText(value:string){if(activeNode.value&&value.trim())mindMap.execCommand('SET_NODE_TEXT',activeNode.value,value.trim())}
function updateTag(value:string){if(activeNode.value)mindMap.execCommand('SET_NODE_TAG',activeNode.value,value?[value]:[])}
function clearTag(){nodeTag.value='';updateTag('')}
function zoom(delta:number){if(mindMap)mindMap.view.setScale(Math.max(0.2,Math.min(3,mindMap.view.scale+delta)))}function fit(){mindMap?.view.fit()}
async function save(){if(!mindMap)return;if(!packageName.value.trim()){ElMessage.warning('请输入用例包名称');return}mindMap.renderer?.textEdit?.hideEditTextBox();saving.value=true;try{const payload={...(editingId===null?{}:{id:editingId}),name:packageName.value.trim(),description:'',content:currentContent()};const response=await api.saveTestCasePackage(payload);editingId=response.data.id;packageName.value=payload.name;ElMessage.success('用例包已保存入库');if(isNew)void router.replace(`/testcase/packages/${editingId}/edit`)}catch(e){ElMessage.error((e as Error).message)}finally{saving.value=false}}
function back(){return router.push('/testcase/packages')}
onMounted(()=>void load());onBeforeUnmount(()=>{mindMap?.destroy();mindMap=null})
</script>
<style scoped>.mind-editor{height:calc(100vh - 118px);background:#fff;display:flex;flex-direction:column;border:1px solid #e6eaf0}.editor-toolbar{height:58px;display:flex;align-items:center;justify-content:space-between;padding:0 16px;border-bottom:1px solid #e6eaf0}.toolbar-left,.toolbar-center{display:flex;align-items:center;gap:8px}.package-name{width:260px}.editor-body{display:flex;min-height:0;flex:1}.mindmap-container{flex:1;min-width:0}.node-panel{width:260px;padding:18px;border-left:1px solid #e6eaf0;background:#fbfcfe}.node-panel h4{margin:0 0 18px;color:#1f2937}</style>
